### ISSUE TITLE
add-auth-token 요청 기능 추가 바랍니다

### ISSUE THREAD

**Issue by key-del-jeeinho** [Promotion-official/AmongAuth-AuthServer#2]
#1 PR 에서 
```
# TODO DB 연동하여, 각 이메일과 client_id 쌍을 만들어, 액세스토큰 중복 체크
```
해당 주석 있는부분에서 among-api 측에
```curl
-curl -X POST\
-h AuthToken:어스서버 인증키
www.among-api.com/token/add-auth-token
 -d "target_token" : "추가할 토큰"
```

해당 리퀘스트 보내도록 해주실 수 있나요??
www.among-api.com 은 더미 도메인으로, configuration 으로 설정가능하게 해주세요

**Comment by sunrabbit123** [comment]
레거시 주석이네요, 해당 유저에 대한 정보를 받아와 토큰화를 하는 것은 `POST /get_token`에서 하는 역할이기때문에, 거기에 맞춰서 작업을 하도록 하겠습니다.

원하는 기능을 다시 정리해보자면
`access_token`을 생성할 때, 해당 서버에도 `access_token`을 추가하도록 하는 기능인 것 같습니다.

다만 질문이 있다면 `AuthToken`의 경우, 인증키의 역할이며 인증의 역할을 하는 값인데 로그에 그대로 값이 노출되는 `url param`의 형태보다는 `HTTP` 에서 정의한 `Authorization 헤더`를 이용하는 것이 좋다고 여겨집니다.

어떻게 생각하시나요?

**Comment by key-del-jeeinho** [comment]
이전에 디스코드의 채팅을 급히 복붙해서 작성한 이슈라서 헤더에 넣기로 한점을 반영하지 못하였네요 수정하겠습니다 😄

**Comment by sunrabbit123** [comment]
혹시
```curl
-curl -X POST\
-h AuthToken:어스서버 인증키
www.among-api.com/token/add-auth-token
 -d "target_token" : "추가할 토큰"
```
에서

```curl
-curl -X POST\
-H "Authorization: {Auth Key}" 
www.among-api.com/token/add-auth-token
 -d "target_token" : "추가할 토큰"
```
를 잘못쓰신건가요 

새로운 헤더를 만들어서 사용하기보다는 기존에 있는 인증헤더를 사용하는것이 좋다고 생각됩니다.
혹여나 실수하신거라면 후자로 작업을 진행하도록 하겠습니다 :D

**Comment by key-del-jeeinho** [comment]
네 잘못썻네요

**Comment by sunrabbit123** [comment]
#3 에서 다루니 그쪽으로 해당 스레드를 이동하도록 하겠습니다 :D
